spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/iventario
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver